# Generated by Django 3.0.8 on 2020-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lucky_number',
            field=models.IntegerField(default=1, max_length=30),
        ),
    ]
